### ISSUE TITLE
error with torch-encoding

### ISSUE THREAD

**Issue by XAVILLA** [isl-org/lang-seg#6]
Hi! Thanks for the great work

I can't seem to import encoding after following the installation steps. The error I got is "cannot import name 'gpu' from partially initialized module 'encoding' (most likely due to a circular import)". Can you please let me know whether you know the cause of this issue? Thanks!

**Comment by XAVILLA** [comment]
Can you please share the system/software configuration you used?

**Comment by XAVILLA** [comment]
resolved!

**Comment by Zacchaeus00** [comment]
> resolved!

Hi @XAVILLA , I met the same issue. Could you please let me know how you solved it? Thanks!

**Comment by Zacchaeus00** [comment]
resolved! (update cuda toolkit)

**Comment by joshmyersdean** [comment]
Hi @Zacchaeus14, could you please share what you did to get this to work?

Thank you!

**Comment by Zacchaeus00** [comment]
> Hi @Zacchaeus14, could you please share what you did to get this to work?
> 
> Thank you!

Please try to use the lastest version of cuda

**Comment by joshmyersdean** [comment]
@Zacchaeus14  I've tried multiple PyTorch installs ranging from 1.7 (with CU 11.0) to the newest version with CU 11.6 but the circular import error still persists. Could you share the commands you used to install?  

@Boyiliee Option 2 does not seem to work either, do you know of the most up to date solution to get everything installed? 

Thank you!
